// AUTH
export const AUTH_SIGN_IN_REQUEST = '@auth/SIGN_IN_REQUEST';
export const AUTH_SIGN_IN_SUCCESS = '@auth/SIGN_IN_SUCCESS';
export const AUTH_SIGN_UP_REQUEST = '@auth/SIGN_UP_REQUEST';
export const AUTH_SIGN_FAILURE = '@auth/SIGN_FAILURE';
export const AUTH_SIGN_OUT = '@auth/SIGN_OUT';

// MEETUP
export const MEETUP_LIST_MEETUP_REQUEST = '@meetup/LIST_MEETUP_REQUEST';
export const MEETUP_LIST_MEETUP_SUCCESS = '@meetup/LIST_MEETUP_SUCCESS';
export const MEETUP_CREATE_MEETUP_REQUEST = '@meetup/CREATE_MEETUP_REQUEST';
export const MEETUP_CREATE_MEETUP_SUCCESS = '@meetup/CREATE_MEETUP_SUCCESS';
export const MEETUP_UPDATE_MEETUP_REQUEST = '@meetup/UPDATE_MEETUP_REQUEST';
export const MEETUP_UPDATE_MEETUP_SUCCESS = '@meetup/UPDATE_MEETUP_SUCCESS';
export const MEETUP_CANCEL_MEETUP = '@meetup/CANCEL_MEETUP';
export const MEETUP_FAILURE = '@meetup/MEETUP_FAILURE';

// USER
export const USER_UPDATE_PROFILE_REQUEST = '@user/UPDATE_PROFILE_REQUEST';
export const USER_UPDATE_PROFILE_SUCCESS = '@user/UPDATE_PROFILE_SUCCESS';
export const USER_UPDATE_PROFILE_FAILURE = '@user/UPDATE_PROFILE_FAILURE';
